server:
  port: 8121

spring:
  datasource:
    url: jdbc:postgresql://localhost:10300/news_dev
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  jpa:
    generate-ddl: false
    open-in-view: false
